/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class visi_crystal_CRinf */

#ifndef _Included_visi_crystal_CRinf
#define _Included_visi_crystal_CRinf
#ifdef __cplusplus
extern "C" {
#endif
#undef visi_crystal_CRinf_REPORT_NAME_LEN
#define visi_crystal_CRinf_REPORT_NAME_LEN 128L
#undef visi_crystal_CRinf_NAME_LEN
#define visi_crystal_CRinf_NAME_LEN 256L
#undef visi_crystal_CRinf_PROMPT_LEN
#define visi_crystal_CRinf_PROMPT_LEN 256L
#undef visi_crystal_CRinf_VALUE_LEN
#define visi_crystal_CRinf_VALUE_LEN 256L
#undef visi_crystal_CRinf_EDITMASK_LEN
#define visi_crystal_CRinf_EDITMASK_LEN 256L
#undef visi_crystal_CRinf_STRING_LEN
#define visi_crystal_CRinf_STRING_LEN 256L
#undef visi_crystal_CRinf_NUMBER
#define visi_crystal_CRinf_NUMBER 0L
#undef visi_crystal_CRinf_CURRENCY
#define visi_crystal_CRinf_CURRENCY 1L
#undef visi_crystal_CRinf_BOOLEAN
#define visi_crystal_CRinf_BOOLEAN 2L
#undef visi_crystal_CRinf_DATE
#define visi_crystal_CRinf_DATE 3L
#undef visi_crystal_CRinf_STRING
#define visi_crystal_CRinf_STRING 4L
#undef visi_crystal_CRinf_DATETIME
#define visi_crystal_CRinf_DATETIME 5L
#undef visi_crystal_CRinf_TIME
#define visi_crystal_CRinf_TIME 6L
#undef visi_crystal_CRinf_INTEGER
#define visi_crystal_CRinf_INTEGER 7L
#undef visi_crystal_CRinf_COLOR
#define visi_crystal_CRinf_COLOR 8L
#undef visi_crystal_CRinf_CHAR
#define visi_crystal_CRinf_CHAR 9L
#undef visi_crystal_CRinf_LONG
#define visi_crystal_CRinf_LONG 10L
#undef visi_crystal_CRinf_NOVALUE
#define visi_crystal_CRinf_NOVALUE 100L
#undef visi_crystal_CRinf_UNCHANGED
#define visi_crystal_CRinf_UNCHANGED -1L
#undef visi_crystal_CRinf_FALSE
#define visi_crystal_CRinf_FALSE 0L
#undef visi_crystal_CRinf_TRUE
#define visi_crystal_CRinf_TRUE 1L
#undef visi_crystal_CRinf_HTML
#define visi_crystal_CRinf_HTML 1L
#undef visi_crystal_CRinf_XLS
#define visi_crystal_CRinf_XLS 2L
#undef visi_crystal_CRinf_CSV
#define visi_crystal_CRinf_CSV 3L
#undef visi_crystal_CRinf_TEXT
#define visi_crystal_CRinf_TEXT 4L
#undef visi_crystal_CRinf_RTF
#define visi_crystal_CRinf_RTF 5L
#undef visi_crystal_CRinf_WORDWIN
#define visi_crystal_CRinf_WORDWIN 6L
/* Inaccessible static: instance */
/*
 * Class:     visi_crystal_CRinf
 * Method:    open
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_open
  (JNIEnv *, jobject);

/*
 * Class:     visi_crystal_CRinf
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_visi_crystal_CRinf_close
  (JNIEnv *, jobject);

/*
 * Class:     visi_crystal_CRinf
 * Method:    setNthTableLogOnInfo
 * Signature: (SLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_setNthTableLogOnInfo
  (JNIEnv *, jobject, jshort, jshort, jboolean, jstring, jstring, jstring, jstring);
  
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_logOnServer
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);
  
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_logOffServer
  (JNIEnv *, jobject );

/*
 * Class:     visi_crystal_CRinf
 * Method:    openReport
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_openReport
  (JNIEnv *, jobject, jstring);

/*
 * Class:     visi_crystal_CRinf
 * Method:    closeReport
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_closeReport
  (JNIEnv *, jobject, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    openSubReport
 * Signature: (SLjava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_openSubReport
  (JNIEnv *, jobject, jshort, jstring);

/*
 * Class:     visi_crystal_CRinf
 * Method:    closeSubReport
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_closeSubReport
  (JNIEnv *, jobject, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    outputToFile
 * Signature: (SLjava/lang/String;I)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_outputToFile
  (JNIEnv *, jobject, jshort, jstring, jint);

/*
 * Class:     visi_crystal_CRinf
 * Method:    outputToWindow
 * Signature: (SLjava/lang/String;IIII)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_outputToWindow
  (JNIEnv *, jobject, jshort, jstring, jint, jint, jint, jint);

/*
 * Class:     visi_crystal_CRinf
 * Method:    outputToPrinter
 * Signature: (SS)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_outputToPrinter
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    getParameterFieldCount
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_getParameterFieldCount
  (JNIEnv *, jobject, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    setNthParameterField
 * Signature: (SSLvisi/crystal/CRParameterField;)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_setNthParameterField
  (JNIEnv *, jobject, jshort, jshort, jobject);

/*
 * Class:     visi_crystal_CRinf
 * Method:    getNthParameterField
 * Signature: (SS)Lvisi/crystal/CRParameterField;
 */
JNIEXPORT jobject JNICALL Java_visi_crystal_CRinf_getNthParameterField
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    setSelectionFormula
 * Signature: (SLjava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_setSelectionFormula
  (JNIEnv *, jobject, jshort, jstring);

/*
 * Class:     visi_crystal_CRinf
 * Method:    getErrorCode
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_getErrorCode
  (JNIEnv *, jobject, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    getErrorText
 * Signature: (S)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_visi_crystal_CRinf_getErrorText
  (JNIEnv *, jobject, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    testReport
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_testReport
  (JNIEnv *, jobject);

/*
 * Class:     visi_crystal_CRinf
 * Method:    canClose
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_visi_crystal_CRinf_canClose
  (JNIEnv *, jobject);

/*
 * Class:     visi_crystal_CRinf
 * Method:    getSelectedPrinter
 * Signature: (S)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_visi_crystal_CRinf_getSelectedPrinter
  (JNIEnv *, jobject, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    selectPrinter
 * Signature: (SLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Lvisi/crystal/DevMode;)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_selectPrinter
  (JNIEnv *, jobject, jshort, jstring, jstring, jstring, jobject);

/*
 * Class:     visi_crystal_CRinf
 * Method:    pageSetup
 * Signature: (ZLvisi/crystal/DevMode;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_visi_crystal_CRinf_pageSetup
  (JNIEnv *, jobject, jboolean, jobject);

/*
 * Class:     visi_crystal_CRinf
 * Method:    getSPParamCount
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_getSPParamCount
  (JNIEnv *, jobject, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    getSPParam
 * Signature: (SS)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_visi_crystal_CRinf_getSPParam
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    setSPParam
 * Signature: (SSLjava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_setSPParam
  (JNIEnv *, jobject, jshort, jshort, jstring);

/*
 * Class:     visi_crystal_CRinf
 * Method:    setSQLQuery
 * Signature: (SLjava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_setSQLQuery
  (JNIEnv *, jobject, jshort, jstring);

/*
 * Class:     visi_crystal_CRinf
 * Method:    getSQLQuery
 * Signature: (S)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_visi_crystal_CRinf_getSQLQuery
  (JNIEnv *, jobject, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    getSelectionFormula
 * Signature: (S)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_visi_crystal_CRinf_getSelectionFormula
  (JNIEnv *, jobject, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    hasSavedData
 * Signature: (S)Z
 */
JNIEXPORT jboolean JNICALL Java_visi_crystal_CRinf_hasSavedData
  (JNIEnv *, jobject, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    discardSavedData
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_discardSavedData
  (JNIEnv *, jobject, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    isPrintJobFinished
 * Signature: (S)Z
 */
JNIEXPORT jboolean JNICALL Java_visi_crystal_CRinf_isPrintJobFinished
  (JNIEnv *, jobject, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    getPageCount
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_getPageCount
  (JNIEnv *, jobject, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    getFormulaCount
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_getFormulaCount
  (JNIEnv *, jobject, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    getFormula
 * Signature: (SS)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_visi_crystal_CRinf_getFormula__SS
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    getFormula
 * Signature: (SLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_visi_crystal_CRinf_getFormula__SLjava_lang_String_2
  (JNIEnv *, jobject, jshort, jstring);

/*
 * Class:     visi_crystal_CRinf
 * Method:    setFormula
 * Signature: (SLjava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_setFormula
  (JNIEnv *, jobject, jshort, jstring, jstring);

/*
 * Class:     visi_crystal_CRinf
 * Method:    setPrintOptions
 * Signature: (SLvisi/crystal/CRPrintOptions;)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_setPrintOptions
  (JNIEnv *, jobject, jshort, jobject);

/*
 * Class:     visi_crystal_CRinf
 * Method:    getDefaultValuesCount
 * Signature: (SLjava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_getDefaultValuesCount
  (JNIEnv *, jobject, jshort, jstring, jstring);

/*
 * Class:     visi_crystal_CRinf
 * Method:    getCurrentValuesCount
 * Signature: (SLjava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_getCurrentValuesCount
  (JNIEnv *, jobject, jshort, jstring, jstring);

/*
 * Class:     visi_crystal_CRinf
 * Method:    getDefaultValue
 * Signature: (SLjava/lang/String;Ljava/lang/String;S)Lvisi/crystal/CRValue;
 */
JNIEXPORT jobject JNICALL Java_visi_crystal_CRinf_getDefaultValue
  (JNIEnv *, jobject, jshort, jstring, jstring, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    getCurrentValue
 * Signature: (SLjava/lang/String;Ljava/lang/String;S)Lvisi/crystal/CRValue;
 */
JNIEXPORT jobject JNICALL Java_visi_crystal_CRinf_getCurrentValue
  (JNIEnv *, jobject, jshort, jstring, jstring, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    getParameterType
 * Signature: (SS)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_getParameterType
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     visi_crystal_CRinf
 * Method:    exportTo
 * Signature: (SLvisi/crystal/CRExportOptions;)S
 */
JNIEXPORT jshort JNICALL Java_visi_crystal_CRinf_exportTo
  (JNIEnv *, jobject, jshort, jobject);

#ifdef __cplusplus
}
#endif
#endif
