package com.altaprise.webrpts.model;

import dai.shared.cmnSvcs.SessionMetaData;

import oracle.jbo.server.ApplicationModuleImpl;
import dai.shared.csAdapters.csSessionAdapter;
import dai.shared.csAdapters.csSessionAdapterFactory;
import dai.shared.cmnSvcs.csSecurity;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 30 22:44:21 EDT 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
  /**
   * This is the default constructor (do not remove).
   */
   csSessionAdapterFactory _sessionAdapterFactory;
   csSessionAdapter    _sessionAdapter;
   SessionMetaData     _sessionMeta;
   csSecurity          _security;

  public AppModuleImpl() {
    System.out.println("Started Init");
    _sessionAdapterFactory  = csSessionAdapterFactory.getInstance();
    _sessionAdapter  = _sessionAdapterFactory.getSessionAdapter();
    _sessionMeta     = SessionMetaData.getInstance();
  }

  public boolean validateSecurity(String uid, String pwd) {
      try {
          _security = _sessionAdapter.connect(null, //not used at this time
                                                  uid,
                                                  pwd);
      } catch (Exception e) {
          return false;
      }
      _sessionMeta.setClientServerSecurity(_security);

      return true;
  }
}
